-- Create database and schema
CREATE DATABASE IF NOT EXISTS PROJECT_TRANSFORMATION;
USE DATABASE PROJECT_TRANSFORMATION;
CREATE SCHEMA IF NOT EXISTS PROJECT_MANAGEMENT;
USE SCHEMA PROJECT_MANAGEMENT;

-- Projects table
CREATE TABLE IF NOT EXISTS PROJECTS (
    PROJECT_ID VARCHAR(36) PRIMARY KEY,
    PROJECT_NAME VARCHAR(255) NOT NULL,
    PROJECT_TYPE VARCHAR(50) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    PRIORITY VARCHAR(20) NOT NULL,
    START_DATE DATE NOT NULL,
    PLANNED_END_DATE DATE NOT NULL,
    ACTUAL_END_DATE DATE,
    DESCRIPTION TEXT,
    OWNER VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Project Budget table
CREATE TABLE IF NOT EXISTS PROJECT_BUDGET (
    BUDGET_ID VARCHAR(36) PRIMARY KEY,
    PROJECT_ID VARCHAR(36) REFERENCES PROJECTS(PROJECT_ID),
    PLANNED_BUDGET DECIMAL(15,2) NOT NULL,
    ACTUAL_BUDGET DECIMAL(15,2) NOT NULL,
    CURRENCY VARCHAR(3) DEFAULT 'USD',
    FISCAL_YEAR INTEGER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Project Risks table
CREATE TABLE IF NOT EXISTS PROJECT_RISKS (
    RISK_ID VARCHAR(36) PRIMARY KEY,
    PROJECT_ID VARCHAR(36) REFERENCES PROJECTS(PROJECT_ID),
    RISK_TYPE VARCHAR(50) NOT NULL,
    SEVERITY VARCHAR(20) NOT NULL,
    PROBABILITY VARCHAR(20) NOT NULL,
    RISK_DESCRIPTION TEXT NOT NULL,
    MITIGATION_PLAN TEXT,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Project Delays table
CREATE TABLE IF NOT EXISTS PROJECT_DELAYS (
    DELAY_ID VARCHAR(36) PRIMARY KEY,
    PROJECT_ID VARCHAR(36) REFERENCES PROJECTS(PROJECT_ID),
    DELAY_TYPE VARCHAR(50) NOT NULL,
    DELAY_REASON TEXT NOT NULL,
    DELAY_START_DATE DATE NOT NULL,
    DELAY_END_DATE DATE,
    IMPACT_DAYS INTEGER,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Project Milestones table
CREATE TABLE IF NOT EXISTS PROJECT_MILESTONES (
    MILESTONE_ID VARCHAR(36) PRIMARY KEY,
    PROJECT_ID VARCHAR(36) REFERENCES PROJECTS(PROJECT_ID),
    MILESTONE_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PLANNED_DATE DATE NOT NULL,
    ACTUAL_DATE DATE,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create views for common queries
CREATE OR REPLACE VIEW PROJECT_HEALTH_VIEW AS
SELECT 
    p.PROJECT_ID,
    p.PROJECT_NAME,
    p.STATUS,
    COUNT(pr.RISK_ID) as ACTIVE_RISKS,
    COUNT(pd.DELAY_ID) as TOTAL_DELAYS,
    CASE 
        WHEN pb.ACTUAL_BUDGET > pb.PLANNED_BUDGET THEN 1
        ELSE 0
    END as BUDGET_OVERAGE
FROM PROJECTS p
LEFT JOIN PROJECT_BUDGET pb ON p.PROJECT_ID = pb.PROJECT_ID
LEFT JOIN PROJECT_RISKS pr ON p.PROJECT_ID = pr.PROJECT_ID AND pr.STATUS = 'ACTIVE'
LEFT JOIN PROJECT_DELAYS pd ON p.PROJECT_ID = pd.PROJECT_ID
GROUP BY 1, 2, 3, 6; 